---
# title: "raport_kj"
# author: "Karol Jaron"
# date: "6/20/2020"
# output:
  # html_document: default
  # pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(eurostat)
library(tidyverse)
library(dplyr)
library(ggplot2)

dat <- get_eurostat(id = 'sdg_11_40', time_format = 'num', filters = list(time = '2018')) %>%
  mutate(country = label_eurostat(geo, dic = "geo", lang = 'en', custom_dic = c(DE = "Germany")))

```

## liczba samochodów osobowych na 1000 mieszkancow

```{r, include=FALSE}
# liczba samochodów z podzialem na wiek - id: road_eqs_carage
dat_pass_cars_tot <- get_eurostat(id = 'road_eqs_carage', time_format = 'num', filters = list(time = '2018')) %>%
  mutate(country = label_eurostat(geo, dic = "geo", lang = 'en', custom_dic = c(DE = "Germany", XK = "Kosovo"))) %>%
  filter(age == "TOTAL" & !geo %in% c('EU28', 'EU27_2020', 'TR')) %>%
  dplyr::rename(cars_qty = values) %>%
  select(geo, cars_qty, country) %>%
  drop_na()


# liczba samochodów osobowych na 1000 mieszkancow - id: road_eqs_carhab
dat_pass_cars <- get_eurostat(id = 'road_eqs_carhab', time_format = 'num', filters = list(time = '2018')) %>%
  mutate(country = label_eurostat(geo, dic = "geo", lang = 'en', custom_dic = c(DE = "Germany", XK = "Kosovo"))) %>%
  filter(!geo %in% c('EU28', 'EU27_2020', 'TR')) %>%
  select(geo, values, country) %>%
  drop_na()

mapdata_pass_cars <- get_eurostat_geospatial(nuts_level = 0, resolution = 20, output_class = "sf") %>%
  right_join(dat_pass_cars) %>%
  mutate(cat = cut_to_classes(values, n = 4, decimals = 1))
```

```{r, echo=FALSE}
ggplot(dat_pass_cars, aes(x = reorder(country, values), y = values, fill = ifelse(geo == "PL", "Highlighted", "Normal"))) +
  geom_bar(stat = "identity") + 
  theme(legend.position = "none", axis.title.y = element_blank()) +
  labs(title = 'Liczba samochodow osobowych na 1000 mieszkancow, 2018', y = 'Samochody', x = NULL) +
  coord_flip()

ggplot(mapdata_pass_cars, aes(fill = cat)) + 
  scale_fill_brewer(palette = 'Reds') + 
  geom_sf(color = alpha('black', 1/3), alpha = .6) + 
  coord_sf(xlim = c(-20,44), ylim = c(30,70)) +
  labs(title = 'liczba samochodow osobowych, 2017', 
       subtitle = '(na 1000 mieszkancow)', 
       fill = 'samochody',
       caption = 'Mapa 8.')
```

## stosunek liczby zgonow w wypadkach drogowych do liczby samochodow

```{r, include=FALSE}
dat_deaths_pass_cars <- dat %>%
  filter(unit == "NR" & !geo %in% c('EU28', 'EU27_2020', 'TR')) %>%
  select(geo, country, values)  %>%
  dplyr::rename(dat_values = values) %>%
  left_join(dat_pass_cars_tot) %>%
  mutate(rate = dat_values / cars_qty * 100000) %>%
  drop_na()

mapdata_deaths_pass_cars <- get_eurostat_geospatial(nuts_level = 0, resolution = 20, output_class = "sf") %>%
  right_join(dat_deaths_pass_cars) %>%
  mutate(cat = cut_to_classes(rate, n = 4, decimals = 1))# %>%
  #drop_na()
```

```{r, echo=FALSE}
ggplot(dat_deaths_pass_cars, aes(x = reorder(country, rate), y = rate, fill = ifelse(geo == "PL", "Highlighted", "Normal"))) +
  geom_bar(stat = "identity") + 
  theme(legend.position = "none", axis.title.y = element_blank()) +
  labs(title = 'stosunek liczby zgonow w wypadkach drogowych do liczby samochodow, 2018', y = 'liczba zgonów na 100000 samochodow', x = NULL) +
  coord_flip()

ggplot(mapdata_deaths_pass_cars, aes(fill = cat)) + 
  scale_fill_brewer(palette = 'Reds') + 
  geom_sf(color = alpha('black', 1/3), alpha = .6) + 
  coord_sf(xlim = c(-20,44), ylim = c(30,70)) +
  labs(title = 'liczba zgonów, 2017', 
       subtitle = '(na 100000 samochodow osobowych)', 
       fill = 'zgony',
       caption = 'Mapa 9.')
```


